M48
; DRILL file KiCad 10.0.1 date 2026-08-11T12:59:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-11T12:59:20-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.321
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.300
%
G90
G05
T1
X174.801Y-184.713
X177.851Y-239.069
T2
X114.951Y-216.904
X114.951Y-230.904
T3
X117.451Y-214.304
X117.451Y-233.504
M30
