M48
; DRILL file KiCad 10.0.1 date 2026-07-01T12:38:27
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-07-01T12:38:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0520
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0906
%
G90
G05
T1
X6.8819Y-7.2722
X7.002Y-9.4122
T2
X4.5256Y-8.5395
X4.5256Y-9.0907
T3
X4.6241Y-8.4371
X4.6241Y-9.1931
M30
